# @format
---
pr: none

trigger:
  batch: false
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

pool:
  vmImage: ubuntu-22.04

variables:
  AZ_CLI_VERSION: 2.48.0
  JQ_VERSION: 1.6
  YQ_VERSION: 4.33.3
  SOPS_VERSION: 3.7.3
  GOLANG_VERSION: 1.20.4
  NODEJS_VERSION: 18.16.0
  YARN_VERSION: 1.22.5
  SHFMT_VERSION: 3.6.0
  SHELLCHECK_VERSION: 0.9.0
  PIP_VERSION: 23.1.2
  YAMLLINT_VERSION: 1.31.0
  HADOLINT_VERSION: 2.12.0
  HELM_VERSION: 3.12.0
  TERRAFORM_VERSION: 1.4.6
  ANSIBLE_VERSION: 7.5.0
  JMESPATH_VERSION: 1.0.1
  OPENSHIFT_VERSION: 0.13.1
  ANSIBLE_KUBERNETES_VERSION: 2.4.0

stages:
  - template: .azure-pipelines/templates/01_lint.yaml
  - template: .azure-pipelines/templates/02_build.yaml
  - template: .azure-pipelines/templates/03_push.yaml
