# @format
---
pr: none

trigger:
  batch: false
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

pool:
  vmImage: ubuntu-20.04

variables:
  AZ_CLI_VERSION: 2.26.0
  JQ_VERSION: 1.6
  YQ_VERSION: 4.9.8
  SOPS_VERSION: 3.7.1
  GOLANG_VERSION: 1.16.5
  SHFMT_VERSION: 3.3.0
  SHELLCHECK_VERSION: 0.7.2
  PIP_VERSION: 21.1.3
  YAMLLINT_VERSION: 1.26.1
  HADOLINT_VERSION: 2.6.0
  HELM_VERSION: 3.6.2
  TERRAFORM_VERSION: 1.0.2
  ANSIBLE_VERSION: 4.2.0
  JMESPATH_VERSION: 0.10.0
  OPENSHIFT_VERSION: 0.12.1
  ANSIBLE_KUBERNETES_VERSION: 2.0.0

stages:
  - template: .azure-pipelines/templates/01_lint.yaml
  - template: .azure-pipelines/templates/02_build.yaml
  - template: .azure-pipelines/templates/03_push.yaml
